version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y jq
      - wget http://www-eu.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz
      - tar xzf apache-maven-3.5.4-bin.tar.gz
      - ln -s apache-maven-3.5.4 maven
      - sed -i 's/jdbc.password=admin123/jdbc.password=RDS_PASSWORD/' src/main/resources/application.properties
      - sed -i 's/jdbc.username=admin/jdbc.username=RDS_USER/' src/main/resources/application.properties
      - sed -i 's/db01:3306/RDS_URL:3306/' src/main/resources/application.properties
  build:
    commands:
      - mvn install
  post_build:
    commands:
      - mvn package
artifacts:
  files:
    - "**/*"
  base-directory: "target/vprofile-v2"
