- name: Provisioning server
  hosts: all
  become: yes
  tasks:
    - name: Install NTP on CentOS
      yum:
        name: "{{ item }}"
        state: present
      when: ansible_distribution == "CentOS"
      loop:
        - ntp
        - wget
        - git
        - zip
        - unzip

    - name: Install NTP in Ubuntu
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes # apt update
      when: ansible_distribution == "Ubuntu"
      loop:
        - ntp
        - wget
        - git
        - zip
        - unzip

    - name: Start NTP on RedHat
      service:
        name: ntpd
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Start NTP on Debian
      service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

    - name: Add group
      group:
        name: devops
        state: present

    - name: Add Users
      user:
        name: "{{ item }}"
        state: present
        groups: devops
      loop: " {{ usernames }}"
