- name: Setup web server
  hosts: websrvgrp
  become: yes
  tasks:
    - name: Install Apache httpd
      yum:
        name: httpd
        state: present

    - name: Start and enable httpd
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Deploying index.html to web server
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: "0644"
        backup: yes
