Mappings: 
  AmiRegionMap: 
    us-east-1: 
      AMI: "ami-0ff8a91507f77f867"
    us-west-1: 
      AMI: "ami-0bdb828fd58c52235"
    eu-west-1: 
      AMI: "ami-047bb4163c506cd98"
    ap-southeast-1: 
      AMI: "ami-08569b978cc4dfa10"
    ap-northeast-1: 
      AMI: "ami-06cd52961ce9f0d85"
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !FindInMap
        - AmiRegionMap
        - !Ref AWS::Region
        - AMI
      Tags:
        - Key: "Name"
          Value: "MyInstance"
      SecurityGroups:
        - !Ref MySecurityGroup
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Description for group
      VpcId:
        ref: vpc-id
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrBlock: 0.0.0.0/0